# Generated by Django 2.1.7 on 2019-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='focus_cities',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
